version: '3.7'
services:
  elasticsearch:
      
      build:
        context: elasticsearch/
        args:
          ELK_VERSION: $ELK_VERSION
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        - /elastic_search/esdata1:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        ES_JAVA_OPTS: "-Xmx1024m -Xms512m"
        ELASTIC_PASSWORD: changeme
      # ulimits:
      #   nofile:
      #     soft: 65536
      #     hard: 65536
      #   nproc: 65535
      #   memlock:
      #     soft: -1
      #     hard: -1
      # cap_add:
      #   - ALL
      # privileged: true  
      networks:
        - elk
  # elasticsearch02:
  #   image: es2
  #   build:
  #     context: elasticsearch/
  #     args:
  #       ELK_VERSION: $ELK_VERSION
  #   volumes:
  #     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  #     - esdata2:/usr/share/elasticsearch/data
   
  #   environment:
  #     ES_JAVA_OPTS: "-Xmx1024m -Xms512m"
  #     ELASTIC_PASSWORD: changeme
  #   ulimits:
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #     nproc: 65535
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   cap_add:
  #     - ALL
  #   privileged: true  
  #   networks:
  #     - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/jdbc_driver_library:/usr/share/logstash/jdbc_driver_library:ro
      - ./logstash/jdbc_driver_library/mssql-jdbc-6.4.0.jre9.jar:/usr/share/logstash/logstash-core/lib/jars/mssql-jdbc-6.4.0.jre9.jar:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      #LS_JAVA_OPTS: -Xmx1g -Xms1g
      LS_JAVA_OPTS: "-Xmx512m -Xms256m"   
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
    

   